# ----------- CONFIGURABLE START -----------
title:            lovelejess
description:      decide who you want to be and go be it.
url:              "http://lovelejess.github.io/"
signoff:          lovelejess
baseurl:          ""
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-49936424-2

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /post
  - name:         Twitter
    url:          https://www.twitter.com/lovelejess
    external:     true
  - name:         LinkedIn
    url:          https://www.linkedin.com/in/lejessica
    external:     true
  - name:         GitHub
    url:          http://github.com/lovelejess
    external:     true
  - name:         Email
    url:          mailto:jessicaduongle@gmail.com  
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"